version: "3.8"

services:
    latex:
        build:
            context: .
            args:
                USER_UID: "${PUID}"
                USER_GID: "${PGID}"
        volumes:
            - .:/workspace
        working_dir: /workspace
        command: ./make.sh
        user: "${PUID}:${PGID}"
